#[path = "lib/app.rs"]
pub mod app;
#[path = "lib/clock.rs"]
pub mod clock;
#[path = "lib/config.rs"]
pub mod config;
#[path = "lib/date.rs"]
pub mod date;
#[path = "lib/storage.rs"]
pub mod storage;
#[path = "lib/task.rs"]
pub mod task;
#[path = "lib/ui.rs"]
pub mod ui;
